AMREX_HOME ?= ../../../../../../amrex

DEBUG	= TRUE
DEBUG	= FALSE

DIM	= 3

COMP    = gcc

TINY_PROFILE  = TRUE
USE_PARTICLES = TRUE

PRECISION     = DOUBLE

USE_MPI       = FALSE
USE_OMP       = FALSE
USE_ACC       = FALSE
USE_SYCL      = TRUE

BL_NO_FORT    = TRUE

Bpack   := ../CUDA/Make.package 
Blocs   := ../CUDA 

include ../../Make.EMPIC
